/**
 * Target Resolver
 *
 * Resolves abstract target descriptions ("a friendly unit", "an enemy unit here",
 * "all units") into actual card IDs on the board.
 *
 * Target types from the parser:
 * - { type: "self" }           → the source card
 * - { type: "unit" }           → any unit on the board
 * - { type: "unit", controller: "friendly" }  → a friendly unit
 * - { type: "unit", controller: "enemy" }     → an enemy unit
 * - { type: "gear" }           → any gear
 * - { type: "card" }           → any card
 * - { type: "player" }         → a player (for effects like "each player")
 */

import type {
  CardId as CoreCardId,
  PlayerId as CorePlayerId,
  ZoneId as CoreZoneId,
} from "@tcg/core";
import { getGlobalCardRegistry } from "../operations/card-lookup";
import type { RiftboundGameState } from "../types";

/**
 * Simplified target descriptor (from parser output).
 */
export interface TargetDescriptor {
  readonly type: string;
  readonly controller?: "friendly" | "enemy" | "any";
  readonly location?: string;
  readonly filter?: Record<string, unknown>;
  /**
   * How many candidates this descriptor resolves to.
   *
   * Shapes (all generated by the parser in
   * `riftbound-cards/src/parser/parsers/target-parser.ts`):
   *   - `number`                   — exactly N (default 1; "a"/"an" → 1)
   *   - `"all"`                    — every matching candidate
   *   - `{ upTo: N }`              — 0..N matching candidates ("up to 2 units")
   *   - `{ atLeast: N }`           — N..all matching candidates ("at least 2 units")
   *
   * In scenario-driven engine runs (no human chooser), the resolver picks the
   * MAXIMUM allowed by `upTo` (i.e. `min(N, candidates)`, the maximally-
   * impactful answer) and ALL available for `atLeast` (an effect text reading
   * "at least N" can target every legal candidate; if fewer than N exist the
   * effect simply targets all of them).
   */
  readonly quantity?:
    | number
    | "all"
    | { readonly upTo: number }
    | { readonly atLeast: number };
  /**
   * Direct reference to a known card instance. Used by:
   *   1. Effects that stash a chosen target into `pendingValue` and later
   *      reference it (sequence/choice-with-name targeting).
   *   2. Sandbox tests that need to point an effect at a specific card.
   *
   * When `cardId` is set, the resolver ignores `type/controller/location`
   * filters and just returns [cardId] (if the card is alive on the board).
   * The shape is `{ type: "specific-card", cardId: "..." }` by convention.
   */
  readonly cardId?: string;
  /**
   * Direct references to multiple card instances. Used by test/sandbox flows
   * that need to point an effect at a specific list of cards
   * (e.g., `{ type: "specific", cardIds: ["card-a", "card-b"] }`).
   */
  readonly cardIds?: readonly string[];
}

/**
 * Context for resolving targets.
 */
export interface TargetResolverContext {
  readonly playerId: string;
  readonly sourceCardId: string;
  readonly sourceZone?: string;
  readonly draft: RiftboundGameState;
  readonly zones: {
    getCardsInZone: (zoneId: CoreZoneId, playerId?: CorePlayerId) => CoreCardId[];
    getCardZone: (cardId: CoreCardId) => string | undefined;
  };
  readonly cards: {
    getCardOwner: (cardId: CoreCardId) => string | undefined;
    /**
     * Read the current controller of a card. Rule 187 / 174: "friendly"
     * and "enemy" relations are determined by CONTROLLER, not owner — a
     * unit taken via Hostile Takeover is "friendly" to its new
     * controller for as long as it's controlled. Falls back to owner
     * when the engine doesn't expose controller separately.
     */
    getCardController?: (cardId: CoreCardId) => string | undefined;
  };
}

/**
 * Resolve a target descriptor to actual card IDs.
 *
 * @param target - The target descriptor from the parsed ability
 * @param ctx - Resolution context
 * @returns Array of resolved card IDs (may be empty if no valid targets)
 */
export function resolveTarget(
  target: TargetDescriptor | undefined,
  ctx: TargetResolverContext,
): string[] {
  if (!target) {
    return [];
  }

  // Self target
  if (target.type === "self") {
    return [ctx.sourceCardId];
  }

  // Specific card by ID — used for stored references (pending-value /
  // Sequenced effects) and for sandbox tests that point an effect at a
  // Known card instance directly. Returns the card if it currently exists,
  // Regardless of zone (the caller's effect — `play`, `take-control` —
  // Applies its own zone semantics).
  if (target.cardId) {
    const zone = ctx.zones.getCardZone(target.cardId as CoreCardId);
    return zone ? [target.cardId] : [];
  }

  // Rule 813 Deathknell — "play me/it from your trash" target mode. The
  // Dying card has already moved to trash by the time the Deathknell trigger
  // Resolves, so a normal board-scope target descriptor would not see it.
  // The dispatcher pushes each dying card onto `state.recentDeaths` for the
  // Duration of the current dispatch cascade; this filter reads from that
  // Log. Supports a controller filter ("from YOUR trash" vs "from an
  // OPPONENT's trash"). See `dispatchUnitDied` in `events/dispatcher.ts`.
  if (target.location === "just-died-trash") {
    const recent = (ctx.draft as { recentDeaths?: { cardId: string; owner: string }[] })
      .recentDeaths;
    if (!recent || recent.length === 0) {
      return [];
    }
    // For "just-died-trash" the "controller" filter applies to the OWNER of
    // The dying card (a trash zone has no controller in the rule sense).
    let pool = [...recent];
    if (target.controller === "friendly") {
      pool = pool.filter((r) => r.owner === ctx.playerId);
    } else if (target.controller === "enemy") {
      pool = pool.filter((r) => r.owner !== ctx.playerId && r.owner !== "");
    }
    // Apply card-type filter if provided.
    if (target.type === "unit" || target.type === "gear" || target.type === "equipment") {
      pool = pool.filter((r) => {
        const def = getGlobalCardRegistry().get(r.cardId);
        if (target.type === "unit") {return def?.cardType === "unit";}
        return def?.cardType === "gear" || def?.cardType === "equipment";
      });
    }
    const ids = pool.map((r) => r.cardId);
    if (target.quantity === "all") {
      return ids;
    }
    const count = typeof target.quantity === "number" ? target.quantity : 1;
    return ids.slice(0, count);
  }

  // Collect candidate cards from the board
  const candidates = getBoardCardIds(ctx);

  // Filter by card type
  const registry = getGlobalCardRegistry();
  let filtered = candidates;

  if (target.type === "unit") {
    filtered = filtered.filter((id) => {
      const def = registry.get(id);
      return def?.cardType === "unit";
    });
  } else if (target.type === "gear" || target.type === "equipment") {
    filtered = filtered.filter((id) => {
      const def = registry.get(id);
      return def?.cardType === "gear" || def?.cardType === "equipment";
    });
  } else if (target.type === "permanent") {
    filtered = filtered.filter((id) => {
      const def = registry.get(id);
      return def?.cardType === "unit" || def?.cardType === "gear" || def?.cardType === "equipment";
    });
  }

  // Filter by controller — rule 187 / 174: "friendly"/"enemy" is determined
  // By the CURRENT controller, not the owner. After a take-control (Hostile
  // Takeover), the taken unit is "friendly" to its new controller for the
  // Duration of the control change. Fall back to owner when the engine
  // Doesn't expose `getCardController` (e.g. unit-test stubs).
  const controllerOf = (id: string): string => {
    const c = ctx.cards.getCardController?.(id as CoreCardId);
    return (c ?? ctx.cards.getCardOwner(id as CoreCardId) ?? "") as string;
  };
  if (target.controller === "friendly") {
    filtered = filtered.filter((id) => controllerOf(id) === ctx.playerId);
  } else if (target.controller === "enemy") {
    filtered = filtered.filter((id) => {
      const c = controllerOf(id);
      return c !== ctx.playerId && c !== "";
    });
  }

  // Filter by location
  if (target.location === "here" && ctx.sourceZone) {
    filtered = filtered.filter((id) => {
      const zone = ctx.zones.getCardZone(id as CoreCardId);
      return zone === ctx.sourceZone;
    });
  } else if (target.location === "base") {
    filtered = filtered.filter((id) => {
      const zone = ctx.zones.getCardZone(id as CoreCardId);
      return zone === "base";
    });
  } else if (target.location?.startsWith("battlefield")) {
    filtered = filtered.filter((id) => {
      const zone = ctx.zones.getCardZone(id as CoreCardId) ?? "";
      return zone.startsWith("battlefield");
    });
  }

  // Exclude self (unless explicitly targeting self)
  if (target.type !== "self") {
    filtered = filtered.filter((id) => id !== ctx.sourceCardId);
  }

  // Apply quantity limit. See `TargetDescriptor.quantity` doc for the four
  // Shapes. The resolver is deterministic (no chooser) so:
  //   - `"all"` → every matching candidate
  //   - `{ upTo: N }` → up to N (i.e. `min(N, candidates.length)`)
  //   - `{ atLeast: N }` → all candidates (caller's effect handles N validity)
  //   - `number` → exactly N (slice; if fewer candidates, return what's there)
  //   - undefined → exactly 1 (back-compat default)
  if (target.quantity === "all") {
    return filtered;
  }
  if (typeof target.quantity === "object" && target.quantity !== null) {
    if ("upTo" in target.quantity) {
      return filtered.slice(0, Math.max(0, target.quantity.upTo));
    }
    if ("atLeast" in target.quantity) {
      return filtered;
    }
  }
  const count = typeof target.quantity === "number" ? target.quantity : 1;
  return filtered.slice(0, count);
}

/**
 * Get all card IDs currently on the board (base + battlefields).
 */
function getBoardCardIds(ctx: TargetResolverContext): string[] {
  const ids: string[] = [];

  // Base cards for all players
  for (const playerId of Object.keys(ctx.draft.players)) {
    const baseCards = ctx.zones.getCardsInZone("base" as CoreZoneId, playerId as CorePlayerId);
    ids.push(...baseCards.map((c) => c as string));
  }

  // Battlefield cards
  for (const bfId of Object.keys(ctx.draft.battlefields)) {
    const bfCards = ctx.zones.getCardsInZone(`battlefield-${bfId}` as CoreZoneId);
    ids.push(...bfCards.map((c) => c as string));
  }

  // Battlefield row cards (battlefield cards themselves)
  const battlefieldRowCards = ctx.zones.getCardsInZone("battlefieldRow" as CoreZoneId);
  ids.push(...battlefieldRowCards.map((c) => c as string));

  // NOTE: Champion zone is intentionally excluded. Cards in the champion zone
  // Have not been played to the board and are not valid targets for board-
  // Targeting effects. Champions must be played (paid for) from the champion
  // Zone to the base before they become targetable.

  return ids;
}
