/**
 * Riftbound Deck-Action Moves (W12)
 *
 * Moves surfaced through the enriched top-deck peek dialog:
 *   - peekTopN               private look at the top N
 *   - placeCardsOnTopOfDeckInOrder ordered insertion onto deck top
 *   - revealTopToOpponent    public reveal of the top N
 *   - recycleMany            batch recycle
 *   - sendToHand             move a card from anywhere into its hand
 *
 * These moves touch the main deck's ordering, so they use the zone
 * operations API with explicit `position` hints to preserve the order
 * the player chose.
 */

import type {
  CardId as CoreCardId,
  PlayerId as CorePlayerId,
  ZoneId as CoreZoneId,
  GameMoveDefinitions,
} from "@tcg/core";
import type { RiftboundCardMeta, RiftboundGameState, RiftboundMoves } from "../../types";

const MAIN_DECK_ZONE = "mainDeck" as CoreZoneId;
const HAND_ZONE = "hand" as CoreZoneId;

/**
 * Deck / peek move definitions.
 */
export const deckActionMoves: Partial<
  GameMoveDefinitions<RiftboundGameState, RiftboundMoves, RiftboundCardMeta, unknown>
> = {
  /**
   * Privately peek at the top N cards of a player's main deck.
   *
   * This move is a no-op on game state — the UI reads the top cards
   * directly from the deck zone snapshot when the player invokes
   * "Look at 1 more". The move still runs through the engine so that
   * the action shows up in the match log (via `formatMoveLog`) and in
   * the replay history, making peeks auditable during rewind/replay.
   */
  peekTopN: {
    reducer: () => {
      // Intentional no-op: the peek is a pure information-disclosure
      // Action from the player's own perspective. The match log entry
      // Generated by the narrator is the observable side effect.
    },
  },

  /**
   * Place a list of cards on top of the main deck, preserving order.
   *
   * The first ID in the array becomes the very top of the deck. We
   * insert from the last ID to the first so each `position: "top"`
   * push puts the next card above the previous one, ending with the
   * intended top card at index 0.
   */
  placeCardsOnTopOfDeckInOrder: {
    reducer: (_draft, context) => {
      const { cardIds } = context.params;
      if (!Array.isArray(cardIds) || cardIds.length === 0) {
        return;
      }
      for (let i = cardIds.length - 1; i >= 0; i--) {
        const cardId = cardIds[i];
        if (!cardId) {
          continue;
        }
        context.zones.moveCard({
          cardId: cardId as CoreCardId,
          position: "top",
          targetZoneId: MAIN_DECK_ZONE,
        });
      }
    },
  },

  /**
   * Publicly reveal the top N cards to the opponent.
   *
   * Like `peekTopN`, this is a no-op on game state — the match log
   * entry is the observable side effect. The UI can expand the deck
   * preview to show the revealed cards based on the narrator event.
   */
  revealTopToOpponent: {
    reducer: () => {
      // Intentional no-op: see comment on peekTopN.
    },
  },

  /**
   * Batch recycle: send every provided card to the bottom of its
   * owner's main deck. Clears transient counters on each card so the
   * recycled card re-enters the deck in a clean state.
   */
  recycleMany: {
    reducer: (_draft, context) => {
      const { cardIds } = context.params;
      if (!Array.isArray(cardIds) || cardIds.length === 0) {
        return;
      }
      for (const cardId of cardIds) {
        if (!cardId) {
          continue;
        }
        context.counters.clearAllCounters(cardId as CoreCardId);
        context.zones.moveCard({
          cardId: cardId as CoreCardId,
          position: "bottom",
          targetZoneId: MAIN_DECK_ZONE,
        });
      }
    },
  },

  /**
   * Move a card from wherever it currently is into its owner's hand.
   *
   * Used by the W12 peek dialog's "To hand" action and by sandbox
   * tools that pull a specific card out of an arbitrary zone. The
   * framework's `moveCard` handles the source-zone lookup; we scope
   * the target to the card's owner so shared zones don't leak.
   */
  sendToHand: {
    reducer: (_draft, context) => {
      const { cardId } = context.params;
      const owner = context.cards.getCardOwner(cardId as CoreCardId) as
        | CorePlayerId
        | undefined;
      // Clear transient counters so damage/stun/buffs don't follow
      // The card into the hand — matches the behavior of `recycleCard`.
      context.counters.clearAllCounters(cardId as CoreCardId);
      context.zones.moveCard({
        cardId: cardId as CoreCardId,
        targetZoneId: HAND_ZONE,
        // `moveCard` routes cards into the zone registered for the
        // Owner automatically; owner is used implicitly by hand zones.
      });
      // Suppress unused warning — owner may be needed in the future
      // To disambiguate hand ownership, but the core zone system keys
      // Hands by owner via the card's current metadata lookup.
      void owner;
    },
  },
};
